# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  

  desc "Deploy a beta version to the Google Play"
  lane :beta do
      store_password = "Jijopaul08$"
      key_password = "Jijopaul08$"
      releaseFilePath ="${HOME}/xkcdcomic"

    gradle( task: 'bundle',
               build_type: 'Release',
                properties: {
                       "android.injected.signing.store.file" => releaseFilePath,
                       "android.injected.signing.store.password" => store_password,
                       "android.injected.signing.key.alias" => "xkcdkey",
                       "android.injected.signing.key.password" => key_password,
                     })
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
