# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  

  desc "Deploy a beta version to the Google Play"
  lane :beta do
    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    mapping_path = Actions.lane_context[SharedValues::GRADLE_MAPPING_TXT_OUTPUT_PATH]
    version_name =  = get_version_name(
                           gradle_file_path:"project/build.gradle",
                           ext_constant_name:"versionName"
                           )
    print version_name
    version_number = get_version_name(
          gradle_file_path:"project/build.gradle",
                                   ext_constant_name:"versionCode"
    )
    print version_number
    store_password = ENV['BITRISEIO_ANDROID_KEYSTORE_PASSWORD']
    key_password = System.getenv("BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD")
    key_password = ENV['BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD']
    releaseFilePath = File.absolute_path "../xkcdcomic"

    gradle( task: 'bundle',
           build_type: 'Release',
            properties: {
                   "android.injected.signing.store.file" => releaseFilePath,
                   "android.injected.signing.store.password" => store_password,
                    "android.injected.signing.key.alias" => ENV['BITRISEIO_ANDROID_KEYSTORE_ALIAS'],
                   "android.injected.signing.key.password" => key_password,
                 })

    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
